services:
  backend:
    build:
      context: .  # root folder
      dockerfile: Dockerfile.backend
    container_name: crud-backend
    ports:
      - "8000:8000"
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: .  # root folder
      dockerfile: Dockerfile.frontend
    container_name: crud-frontend
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
